# Setup
title:               Matahari Oral History Project
tagline:             'Documenting Domestic Workers In Boston'
description:         'Content Might Go Here'
url:
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Connor Haugh
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
